# Generated by Django 4.1.3 on 2022-12-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='date updated'),
        ),
    ]
