# Generated by Django 4.1.3 on 2022-12-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogpost_date_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date_published',
            field=models.DateField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
